-- MySQL Script generated by MySQL Workbench
-- Wed Oct 18 12:26:34 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nombreusuario` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `foto_contenido` LONGBLOB NOT NULL,
  `foto_tipo` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensaje` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(140) NOT NULL,
  `imagen_contenido` LONGBLOB NULL,
  `imagen_tipo` VARCHAR(4) NULL,
  `usuarios_id` INT NOT NULL,
  `fechayhora` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mensaje_usuarios_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_mensaje_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siguiendo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siguiendo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `usuarioseguido_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_siguiendo_usuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_siguiendo_usuarios2_idx` (`usuarioseguido_id` ASC),
  CONSTRAINT `fk_siguiendo_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_siguiendo_usuarios2`
    FOREIGN KEY (`usuarioseguido_id`)
    REFERENCES `usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `me_gusta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `me_gusta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `mensaje_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_gusta_usuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_gusta_mensaje1_idx` (`mensaje_id` ASC),
  CONSTRAINT `fk_gusta_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gusta_mensaje1`
    FOREIGN KEY (`mensaje_id`)
    REFERENCES `mensaje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;